### ISSUE TITLE
Sample .virtu file

### ISSUE THREAD

**Issue by scitesy** [vbmithr/ocaml-kraken#2]
Would it be possible to have a sample .virtu file added to the repository? I can't seem to get the expression correct. I am new to S expressions.
This is my latest incorrect attempt:
((key "old")
 (secret "type123")
 (passphrase "okey")
 (quote ()))
What am I doing wrong?

**Comment by vbmithr** [comment]
I'm going to replace that virtu file thing (was a bad idea) by just environment variable. Doing that now.

**Comment by scitesy** [comment]
Ok. Thank you!
